"""Boundary contracts. Services depend on these ports, never concrete adapters."""
from dataclasses import dataclass, field
from enum import Enum
from typing import ContextManager, Protocol
from ..domain.commands import VehicleCommand


class Record(Enum):
    STATE = "state"
    COMMAND_RESULT = "command_result"
    COMMAND_SETUP = "command_setup"
    ACTION_NOTICE = "action_notice"


class Clock(Protocol):
    def now(self) -> float: ...
    def monotonic(self) -> float: ...
    def sleep(self, seconds: float) -> None: ...


class Profile(Protocol):
    def read(self, record: Record) -> dict: ...
    def write(self, record: Record, value: dict) -> None: ...
    def delete(self, record: Record) -> None: ...
    def configuration(self) -> dict: ...
    def save_configuration(self, config: dict, changes: dict | None = None) -> dict: ...
    def locked(self, blocking: bool = True) -> ContextManager: ...


class CredentialVault(Protocol):
    def get(self, account: str) -> str | None: ...
    def set(self, account: str, value: str) -> None: ...
    def delete(self, account: str) -> None: ...


class VehicleGateway(Protocol):
    def vehicles(self) -> list[dict]: ...
    def granted_scopes(self) -> set[str]: ...
    def reading(self, vin: str, include_location: bool, now: float) -> dict: ...
    def connection_state(self, vin: str) -> str: ...
    def capabilities(self, vin: str) -> dict: ...
    def execute(self, command: VehicleCommand) -> str | None: ...


class MapMedia(Protocol):
    def identity(self, cache: dict) -> str | None: ...
    def saved(self, cache: dict) -> bytes | None: ...
    def fetch(self, cache: dict) -> bytes: ...
    def save(self, data: bytes) -> str: ...
    def delete(self) -> None: ...


class Geocoder(Protocol):
    def address(self, point: tuple[float, float]) -> str | None: ...


class AccountFlow(Protocol):
    def configure(self) -> None: ...
    def provision(self, config: dict, launch: bool) -> None: ...
    def authorize(self, config: dict, launch: bool) -> None: ...
    def register(self, config: dict) -> None: ...


@dataclass(frozen=True)
class Request:
    command: str = "menu"
    value: str | None = None
    vin: str | None = None
    temperature: str | None = None
    no_browser: bool = False


@dataclass
class Result:
    config: dict
    cache: dict | None = None
    demo: bool = False
    messages: list[str] = field(default_factory=list)
    error: str | None = None


@dataclass(frozen=True)
class MenuContext:
    """All external inputs required by the pure xBar renderer."""
    now: float
    launcher: str
    icon_image: bytes | None = None
    map_image: bytes | None = None
    report: dict = field(default_factory=dict)
    notice: dict = field(default_factory=dict)
    setup: dict = field(default_factory=dict)


class IdentityProvider(Protocol):
    def authorize(self, config: dict, complete, launch: bool) -> None: ...
    def exchange_code(self, config: dict, code: str) -> str | None: ...
    def register(self, config: dict) -> None: ...


class SettingsInput(Protocol):
    def configure(self) -> None: ...
    def provision(self, config: dict, launch: bool) -> None: ...
